version: 1.0.2.{build}
branches:
  only:
  - master
image: Visual Studio 2017
build_script:
- cmd: dotnet build src\GranSteL.Helpers.Autofac.sln -c Release
test_script:
- cmd: dotnet test "src\GranSteL.Helpers.Autofac.Tests" -c Release